### ISSUE TITLE
Stacks Wallet not processing transaction

### ISSUE THREAD

**Issue by dantrevino** [blockstack/stacks-wallet#125] opened 2020-02-08 21:54 UTC
**Describe the bug**
Stacks wallet just displays "Processing ..." and never submits transactions.

**To Reproduce**
1. Click on Send
2. Add a recipient and amount
4. Add seed phrase
5. The "Processing..." message comes up and never goes away.  Currently 1.25 hrs and counting.

**Expected behavior**
Submitting a transaction actually submits a transaction.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: n/a
 - Version: 10.14.6

**Additional context**

**Comment by yknl** [comment] 2020-02-10 21:13
Thanks for reporting, sometimes this is caused by having insufficient BTC fuel balance to send the transaction. There's a bug with the error display, which will be addressed in an update soon.

**Comment by whiteyhat** [comment] 2020-02-20 10:00
<img width="601" alt="Captura de pantalla 2020-02-20 a las 10 59 31" src="https://user-images.githubusercontent.com/31220861/74922847-2064c780-53d0-11ea-98ef-2c8b27fe50fb.png">


I have enough BTC.. always same error....

**Comment by dantrevino** [comment] 2020-03-22 21:57
@yknl how do we see the bitcoin address associated with the wallet?  I see in the settings how much bitcoin I have, but I want to see the wallet address.

**Comment by yknl** [comment] 2020-03-24 18:59
@dantrevino you can click the "Add BTC" button to see the address.

**Comment by markmhx** [comment] 2020-10-30 16:01
@dantrevino are you still experiencing a problem here?

**Comment by dantrevino** [comment] 2020-11-01 02:00
AFAIK this is still an issue.  I havent tried one of the v1 wallets for a while.

**Closed** 2021-01-08 13:29 UTC
Labels: 3.x, bug, wontfix

**Comment by doffing81** [comment] 2021-01-15 22:58
My wallet is stuck on `Processing...` after entering the seed phrase when trying to send. Is this expected behavior?

**Comment by dantrevino** [comment] 2021-01-15 23:20
> My wallet is stuck on `Processing...` after entering the seed phrase when trying to send. Is this expected behavior?
> 
> Sometimes the seed phrase submenu will disappear clicking outside of it, leaving no way to know what is happening. I am using version 3.1.1
> 
> @dantrevino, were you able to send ever?

Nope but I'm using v4 now and that worked.

**Comment by doffing81** [comment] 2021-01-15 23:29
> Nope but I'm using v4 now and that worked.

Switched to the new release... seems like a send worked.
