### ISSUE TITLE
Resolve pending transactions after encountering "Send Max" bug

### ISSUE THREAD

**Issue by Crypto88mine** [blockstack/stacks-wallet#646] opened 2021-02-25 18:17 UTC
Hello!
Found a bug in Stacks Wallet v.4.1.0.
After several trial (successful) transactions, I sent the remainder of the ~ 664CTX tokens (I pressed "Send max") and transaction was freeze in pending for more than a day. Maybe the wallet has calculated the wrong rest in the balance.
I tried another transaction and got the same result.
The balance is displayed in the wallet and explorer, but it is not possible to send tokens.
I attach screenshots and links. 
How can I send my tokens?
https://explorer.stacks.co/txid/0xb622b5436ac95630b3d317988e05641af9c341aad120bd04ccbf6f6cb3987387?utm_source=stacks-wallet&chain=mainnet
https://explorer.stacks.co/txid/0x186d6f532a720a0e3cf97bcfd8f38422cf89d3f6b26447ecf189cf09e9698790?utm_source=stacks-wallet&chain=mainnet
![Stx wallet](https://user-images.githubusercontent.com/41759799/109197698-5f311880-77ae-11eb-9595-2f78459cfe6a.jpg)

**Comment by markmhx** [comment] 2021-02-26 16:07
Hi! Have any of these transactions settled since the time you created this issue?

We have a known issue (https://github.com/blockstack/stacks-wallet/issues/591) with the "Send Max" button that appears to have affected the third transaction listed in your screenshot (aka the first initiated chronologically). 

I believe the second one listed _should_ have gone through, while the first one listed should eventually fail for lack of balance once the second one is confirmed.

**Comment by Crypto88mine** [comment] 2021-02-28 00:41
Hi! All three frozen transactions disappeared from the wallet.
I made a trial transaction for 30 tokens successfully.
So the problem was that while the tokens are "sending", the balance on the wallet is not decreasing yet. And accordingly, the following transactions fail.
![image_2021-02-27_21-04-45](https://user-images.githubusercontent.com/41759799/109404301-d1a02500-7975-11eb-8dcc-37ce33977724.png)
![stx2](https://user-images.githubusercontent.com/41759799/109404406-d1ecf000-7976-11eb-8c7f-8cd4136adc9d.jpg)

**Comment by markmhx** [comment] 2021-03-01 16:51
Thanks for the update. That appears to be the behavior seen in #591 as well. I'll close this issue out only since we're tracking the related fix on that issue already. 🙏

**Closed by markmhx** 2021-03-01 16:51 UTC
Labels: P1, bug
