### ISSUE TITLE
wallet transition error (1.0 wallet to 4.0.2)

### ISSUE THREAD

**Issue by steverichmond** [blockstack/stacks-wallet#543] opened 2021-01-19 20:40 UTC
I am an original backer (purchased through Coinlist) and had a wallet 1.0 address with a 12 word seed and my allocation of Stacks in it.  I just entered my entity name and seed phrase into the 1.0 wallet (to restore it), and the 1.0 wallet prompted me to return to Coinlist and (on coinlist) enter a new wallet address and verification code.  This does not seem right.

Further, when I enter my wallet 1.0 seed phrase into wallet 4.0.2, it says it does not recognize it as a Stacks seed phrase.  It allows me to create the wallet but there are no Stacks in it.  Please advise.

I notice other discussion of this issue here:
https://discord.com/channels/621759717756370964/625538774230892545/800455023246180423

**Comment by kyranjamie** [comment] 2021-01-20 08:17
The Stacks Wallet, since v1, has only ever generated 24 word phrases. Are you sure you generated this address with the wallet? That warning is there because, while we need to allow valid bip39 seeds for some cases, most users would never have credited STX to these addresses.

A common mix up we're seeing is people confusing up their 24-word wallet phrases with their 12 word "recovery codes" from the Blockstack Browser. Do you have another seed phrase written down somewhere?

**Comment by markmhx** [comment] 2021-01-20 12:40
I'm going to close this out on the belief that the issue is indeed related to the entry of a different 12-word seed created for the Blockstack Browser instead of the 24-word one used to purchase via Coinlist.

@steverichmond please let us know here in the comments, however, if we can continue helping to troubleshoot.

**Closed by markmhx** 2021-01-20 12:40 UTC
