### ISSUE TITLE
[Windows] Difficulty connecting Ledger on Windows

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet#497] opened 2021-01-14 18:08 UTC
Investigate unreliable flow connecting Ledger on Windows. 

**Workaround**
Ensure all other apps using your device are closed, i.e. Ledger Live.

When the Ledger device is open on the Stacks app, and you see this screen:

![image](https://user-images.githubusercontent.com/1618764/104630833-a0a4b300-569b-11eb-8157-c9f29a202a0e.png)

1. Press the back arrow, top left
2. Return to the Connect your Ledger page

You should now be able to press the continue button.

**Comment by markmhx** [comment] 2021-01-20 12:27
Is this something we should ask @timstackblock to help test?

**Comment by markmhx** [comment] 2021-02-18 10:35
This is a duplicate of https://github.com/blockstack/stacks-wallet/issues/614.

**Closed by markmhx** 2021-02-18 10:35 UTC
Labels: P2, bug, windows
