### ISSUE TITLE
Fix indication of cycle length in direct Stacking form

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#674] opened 2021-03-08 15:05 UTC
"6 to 8 days" is inaccurate. Can we display this dynamically using the API? Or replace with a correct static value?

![image](https://user-images.githubusercontent.com/28991/110339018-f8babe80-8027-11eb-9a1c-d2cb9c8dce14.png)

Reported by @jeffdomke

**Comment by aulneau** [comment] 2021-03-08 15:06
We could also display the last cycle length, as that is known information.

**Comment by kyranjamie** [comment] 2021-03-09 13:26
Duplicate of https://github.com/blockstack/stacks-wallet/issues/636 fixed in https://github.com/blockstack/stacks-wallet/pull/638

We can release this with until-burn-ht changes

**Closed** 2021-03-15 14:17 UTC
Labels: P3, bug
