### ISSUE TITLE
[3.1.1] Cannot go past "Browser support" when restoring wallet with Ledger Nano S

### ISSUE THREAD

**Issue by jacopocer** [blockstack/stacks-wallet#581] opened 2021-01-30 16:09 UTC
When using Stacks Wallet 3.1.1 (needed to withdraw BTC), restoring wallet with a Ledger Nano S requires disabling "Browser Support" in the bitcoin app, but that option is not visible anymore with the latest updates.
Restoring the wallet is then not possible and so is the BTC withdrawal.
Any ideas?

**Comment by markmhx** [comment] 2021-02-09 11:48
This appears to be a duplicate of the bug report here: https://github.com/blockstack/stacks-wallet/issues/124

@jacopocer mind emailing me at mark@hiro.so and I'll assist you there given your particular needs in regards to BTC withdrawals?

**Closed by markmhx** 2021-02-09 11:48 UTC
Labels: 3.x
