### ISSUE TITLE
Improve Secret Key validation during entry

### ISSUE THREAD

**Issue by jrosarky** [blockstack/stacks-wallet#526] opened 2021-01-17 23:11 UTC
Hi  Please Help.
   I just downloaded the latest wallet version.
When I try to use my existing wallet 24 word key, it errors at word 12.   I know the key is correct works fine on wallet 3.1.1.
How do I restore my wallet on the new one.    It appears to be looking for a 12 word key... 
ERROR MESSAGE:
It appears you've entered a Secret Key originally created elsewhere than the Stacks Wallet. We recommend you create a new Secret Key with the Stacks Wallet for greater security.

**Comment by fluidvoice** [comment] 2021-01-17 23:18
This happens for me also, the popup happens upon typing word number 15 and I have reproduced this with a 24-word seed generated from both the 3.0.0 wallet and one from the 3.1 wallet.

**Comment by aulneau** [comment] 2021-01-17 23:54
Hi @jrosarky & @fluidvoice,

I have just downloaded v3 (old version) of the wallet, generated a 24 word phrase, and downloaded the latest version 4.0.2 of the stacks wallet, and entered that phase in and it worked correctly. This is on macOS, unfortunately I cannot test on windows / linux. Come tuesday we should have someone around (it's a three day weekend for folks in the US) to take a look and check on windows/linux.

Can you confirm that you're both using 4.0.2, and that your seed phrase is formatted as one line of words, with only one space between each word?

Thanks!

**Comment by jrosarky** [comment] 2021-01-18 00:00
Yes 4.02.        As I enter the seed words seperated by spaces it auto wraps to the next line, but yes one line of words otherwise.

**Comment by stupidusernametoreportissues** [comment] 2021-01-18 00:03
I too am having similar issues, downloaded filename is stacks-wallet.mainnet.v4.0.2, don't now how else to check version.  I encounter this problem on both MacOS and Windows10.  typing the 12th word, 72 character, error message as above

**Comment by fluidvoice** [comment] 2021-01-18 00:08
> I too am having similar issues, downloaded filename is stacks-wallet.mainnet.v4.0.2, don't now how else to check version. I encounter this problem on both MacOS and Windows10. typing the 12th word, 72nd character, error message as above

where did you get your 12 word seed from? The wallets create a 24-word seed.

**Comment by stupidusernametoreportissues** [comment] 2021-01-18 00:12
I have a 24-word seed, it decides that I'm an idiot while I'm typing the  12th word
Big Sur v11.1  Windows 10 Home v 2004

**Comment by aulneau** [comment] 2021-01-18 00:14
I see, if you were to type the words into a text editor, and paste the completed phrase into the wallet, does that work?

**Comment by fluidvoice** [comment] 2021-01-18 00:14
for me it happens on the 15th word. A clue?

**Comment by fluidvoice** [comment] 2021-01-18 00:21
> I see, if you were to type the words into a text editor, and paste the completed phrase into the wallet, does that work?

YES! that just worked for me with v4.0.1 on Ubuntu.

**Comment by jrosarky** [comment] 2021-01-18 00:21
That worked!


________________________________

**Comment by stupidusernametoreportissues** [comment] 2021-01-18 00:22
typing words in editor, copy and pasting in wallet works for me on Windows 10.  I see my old balance same as wallet 3.0.0

**Comment by aulneau** [comment] 2021-01-18 00:23
Ah okay, we are being a bit too eager with validation on the input for the phrase. We should validate the phrase on submission, rather than as you type. I'll make an issue and we'll get it fixed asap! Until then, pasting a completed phrase is what you'll need to do.

**Comment by julianlcarter** [comment] 2021-01-19 21:30
I had Stacks 1.0 wallet. I dowloaded Stacks 4.0.2 wallet and entered my 12 word phrase. 

It is not being accepted. It says "It appears you've entered a Secret Key originally created elsewhere than the Stacks Wallet. We recommend you create a new Secret Key with the Stacks Wallet for greater security."

How do I overcome this? If I continue with the 12 word phrase it shows a 0 balance when there are Stacks in there I know.

**Comment by kyranjamie** [comment] 2021-01-19 21:37
The Stacks Wallet pre version 4 gives 24-word phrases. It's quite possible you're using your Blockstack Browser "Secret Recovery Key" rather than the one given by the Stacks Wallet.

**Comment by julianlcarter** [comment] 2021-01-19 22:49
Thanks. I've got it working. Upgraded to 1.6.1 firmware update on Ledger Nano S. 

Then downloaded Stacks app to Ledger using Ledger Live.

Then opened Stacks 4.0.2 and logged in via Ledger and there they all were.

**Comment by markmhx** [comment] 2021-01-20 10:55
I'm closing this since we'll release a fix shortly as part of v4.0.3.

**Closed** 2021-01-20 19:27 UTC
Labels: 4.x, P2, bug, enhancement
