### ISSUE TITLE
Fix possible nonce issue with sends

### ISSUE THREAD

**Issue by Neyfan** [blockstack/stacks-wallet#648] opened 2021-02-26 16:47 UTC
I wrote to you in support, in ds, to which they answered me: the transaction should fail with something like "insufficient balance", but it will remain in the 256 block mempool, you will need to resend the transaction using the correct amount from that same nonce and higher commission
the wallet won't let you set the nonce, but the cli will be (npm i -g @ stacks / cli). So, according to my calculations, the transaction was already thrown out of the mempool at block 5088, but nothing happened. Maybe I was wrong, then how many blocks do I have left? I hope you can help me, for me it is difficult.By the way, yesterday I decided to try to send a friend to the account 1 stx, but nothing came of it, could this somehow affect the whole situation?
![Безымянный](https://user-images.githubusercontent.com/79596468/109329262-6cf8a380-786b-11eb-91a9-a3447f9d89e4.png)

**Comment by kyranjamie** [comment] 2021-02-27 08:37
Thanks for the report @Neyfan 

Do you mind sharing your address? The problem could either lie either with the API hanging onto these txs, or the wallet locally keeping these txs mistakely.

**Comment by kyranjamie** [comment] 2021-03-16 15:06
Closing this issue as a probable duplicate of https://github.com/blockstack/stacks-wallet/issues/591

**Closed by kyranjamie** 2021-03-16 15:06 UTC
Labels: P2, bug
