### ISSUE TITLE
Fix intermittent Ledger connection error

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#471] opened 2021-01-08 18:30 UTC
Intermittent connection issue when attempting to log into the wallet with your ledger. 

I have logged in successfully but occasionally run into this issue and have to back all the way out to get into the wallet.

<img width="1009" alt="Screen Shot 2021-01-08 at 12 52 23 PM" src="https://user-images.githubusercontent.com/49165468/104051075-8ce9e000-51b5-11eb-995b-514919f5b554.png">

**Comment by markmhx** [comment] 2021-01-19 11:08
I haven't see this in my testing lately. Any of you?

**Comment by kyranjamie** [comment] 2021-01-19 11:12
Yes, especially windows. I have a WIP PR that refactors the Ledger integration more aligned with Electron best practice. Not sure if this will fix these issues but definitely gives us a better base from which to test/debug 
https://github.com/blockstack/stacks-wallet/pull/527

**Comment by markmhx** [comment] 2021-02-18 10:35
This is a duplicate of https://github.com/blockstack/stacks-wallet/issues/614.

**Closed by markmhx** 2021-02-18 10:35 UTC
Labels: P2, bug, windows
