### ISSUE TITLE
Fix Windows detection of Ledger reconnection when opening Stacks app

### ISSUE THREAD

**Issue by clemons7778** [blockstack/stacks-wallet#614] opened 2021-02-15 14:11 UTC
Bug found testing Stacks Wallet build undefined, 4.0.4.

When trying to confirm transaction on Ledger using Stacks desktop wallet, Ledger says "Pending Ledger Review" but doesn't give me the option to confirm or deny the transaction details.  Can't send any STX tokens for stacking.

**Comment by kyranjamie** [comment] 2021-02-15 15:22
@clemons7778 You can proceed past the "Pending Ledger Review" screen by pressing both the buttons on the Ledger at the same time. Does this allow you to proceed and sign transactions correctly?

**Comment by clemons7778** [comment] 2021-02-15 16:42
pressing both buttons on ledger nano doesn't allow me to proceed to sign the transaction.  i have updated ledger live, the stacks app in ledger live and i have v4.0.4 of stacks desktop wallet.  using windows 10

**Comment by kyranjamie** [comment] 2021-02-15 16:50
Nano S or X? 

Try opening the Stacks app on the device before going to the Connect Your Ledger page. Make sure Ledger Live is closed as well, as they can't both work at once.

**Comment by clemons7778** [comment] 2021-02-15 18:06
nano s.  i tried restarting computer.  opening only the stacks wallet desktop app, then connected ledger and attempted to submit and sign transaction.  got stuck on the same "pending ledger review" message on ledger.  clicking both buttons simultaneously only toggles to "stacks ready" screen where i have the option to toggle to expert mode.  no option to sign transaction

**Comment by kyranjamie** [comment] 2021-02-15 18:10
The option to sign a transaction isn't on the Ledger itself. 

With the "Stacks ready" screen open, click _Send_ in the wallet, fill recipient & amount, click _Confirm and Sign_. Only on this screen can you request the Ledger to sign your tx.

**Comment by clemons7778** [comment] 2021-02-15 19:05
right, but here is the series of events that happens:

1. click send in the desktop wallet
2. unlock ledger device
3. stacks desktop wallet recognizes i have my ledger unlocked
4. prompts me to open stacks wallet on ledger
5. open stacks wallet on ledger
6. stacks desktop wallet no longer recognizes i have my ledger unlocked

if i close back out of my stacks wallet on ledger, the desktop stacks wallet shows that my ledger device has been unlocked again.  the disconnect seems to happen only when i open the stacks wallet on ledger

<img width="406" alt="2" src="https://user-images.githubusercontent.com/7807215/107984646-62e6c300-6f96-11eb-8758-c4f1f17c1419.PNG">
<img width="447" alt="1" src="https://user-images.githubusercontent.com/7807215/107984651-6417f000-6f96-11eb-8dd5-df8cdd8bc851.PNG">

**Comment by kyranjamie** [comment] 2021-02-15 19:14
Thanks for the running through these steps @clemons7778, sorry the difficulties here

It looks like there's an issue detecting whether the Ledger's connected. With the Stacks App open before landing on this page, or going back to the previous page, then returning to the _Confirm on your Ledger_, does it detect your Ledger?

**Comment by clemons7778** [comment] 2021-02-15 21:15
i just tried to toggle back and forth.  it still only recognizes that my ledger is connected only if i am on the ledger nano main menu.  once i select the stacks app the ledger is no longer recognized in the stacks desktop wallet app

**Comment by clemons7778** [comment] 2021-02-15 21:16
i really appreciate your help with this.  hopefully we can figure it out

**Comment by kyranjamie** [comment] 2021-02-16 08:28
@clemons7778 I've confirmed your issue, indeed Windows is not detecting the "reconnection" when opening the Stacks app on the device.

As mentioned above, a workaround (that works consistently for me), is to leave the Stacks Ledger app open, and return to the _Confirm on your Ledger_ screen (your last screenshot). We'll fix this asap, however in the meantime this should at least allow you to send your funds.

**Comment by clemons7778** [comment] 2021-02-16 18:59
Thanks a ton for your help with this.  I'm still not having any luck following the suggested steps you outlined.  

Do you expect Leger to fully support the Stacks wallet soon?  I assume that would eliminate the need for the Stacks desktop wallet for Ledger owners and hope that there would still be an option to stack tokens for BTC yield through the Ledger device itself without having to interface with the desktop stacks wallet.

**Comment by markmhx** [comment] 2021-02-17 14:19
@clemons7778 Might you be interested in jumping on a video call so we can help unblock you here? If so, mind choosing a time listed at https://calendly.com/markmhendrickson/meeting ?

**Comment by clemons7778** [comment] 2021-02-17 14:46
That sounds great!  Thanks for reaching out.  I have selected a time slot and look forward to working through this.  I am eager to learn more about this project.

**Comment by markmhx** [comment] 2021-02-18 10:36
We may resolve this issue as part of https://github.com/blockstack/stacks-wallet/pull/527, and it will also resolve itself whenever Ledger removes us from "developer mode" (whichever happens first).

**Comment by clemons7778** [comment] 2021-02-18 17:14
Thanks Mark!  Once you are fully integrated with Ledger, do you expect Ledger to support stacking independent of the native Stacks desktop wallet?

**Comment by markmhx** [comment] 2021-02-19 12:23
You're welcome! That level of support isn't in the works yet. I'm not sure really what it would involve or if it's possible, but it certainly sounds nice. If you know of comparable integrations, I'd love to take a look.

**Comment by clemons7778** [comment] 2021-02-23 21:46
v4.1.0 of stacks wallet fixed this issue.  thanks team and congrats on delegated stacking integration.

**Comment by kyranjamie** [comment] 2021-02-24 11:49
Thrilled to hear this has fixed your issue @clemons7778—though we're not actually sure why these changes have remedied the issue. 

We'll keep this open for now until we can get further confirmation 👍🏼

**Comment by kyranjamie** [comment] 2021-03-16 14:58
Fixed in `4.1.1`

**Closed by kyranjamie** 2021-03-16 14:58 UTC
Labels: P1, bug, support, windows
