### ISSUE TITLE
Fix balance to include all unlocked STX for address

### ISSUE THREAD

**Issue by jlyst** [blockstack/stacks-wallet#608] opened 2021-02-13 03:26 UTC
**Stacks Wallet 4.0.4 total balance** does not match the **explorer available balance** found after clicking `View on Explorer` link in wallet. 

The Stacks Wallet displays a lower balance. The difference between the two displayed balances appears to be the amount of the latest unlocked block in the unlocking schedule. The latest unlocked block is labeled as 'received' in the explorer schedule--so it seems that the balances should match.

Either the two balances should match or a clear explanation for a potential discrepancy should be presented to the user. Wallet running on macOS.

**Comment by ounrequitedo** [comment] 2021-02-13 07:08
I am having the exact same issue on Stacks Wallet v4.0.4 using Ledger as my hardware wallet. My balance is off by the latest amount which from the Explorer Schedule says was Received 02/11/21.

**Comment by aulneau** [comment] 2021-02-13 15:28
Hi there @jlyst @ounrequitedo!

Yes, that is the case currently. There is an underyling API that both the wallet and explorer use to get this data, but currently the explorer is using more-up-to-date information than is available to the wallet. I know the team is hard at work to remedy this, but be sure to know that the view on the explorer is up-to-date and that your tokens are safe! 

If you are at all interested in checking your balances for yourself you can follow this process:

- Use the "Accounts" RPC endpoint on a stacks node: https://stacks-node-api.mainnet.stacks.co/v2/accounts/SPX8T06E8FJQ33CX8YVR9CC6D9DSTF6JE0Y8R7DS?proof=0 (swapping for your address in the URL)
- Get the "balance" JSON field, which looks like "0x0000....". This is an integer in hexadecimal format. You can use a tool like https://www.rapidtables.com/convert/number/hex-to-decimal.html to convert this to a human-readable number. The result is your balance in MicroStacks. 1 STX = 1,000,000 microstacks - so divide that result by 1,000,000 to see your balance in STX.

I will reply to this thread when the API has been updated that the wallet is consuming.

**Comment by ounrequitedo** [comment] 2021-02-13 17:12
So how do I use the wallet to send the blocked stx to a stacking pool if the wallet won't see the token? If nothing changes and the wallet continues as-is, how delayed is the API used by the wallet so that I can send my token to the pool to join the rest of my stx?

**Comment by Esharifov** [comment] 2021-02-13 17:41
Exact same issue on my end as well, latest (Feb 11) unlocked tokens aren't retrieved in the wallet version [v4.0.4].

Not able to send the token to a different address either, since client disables "Send" button when the balance is 0 ([in explorer balance isn't 0](https://explorer.stacks.co/address/SP1MVHQKEHJT6256AB704MPNYVX2RJJQ4MQ2RF8W0?utm_source=stacks-wallet&chain=mainnet))

![image](https://user-images.githubusercontent.com/13299214/107856817-a814c480-6ddf-11eb-940b-c5a181f91e30.png)

**Comment by markmhx** [comment] 2021-02-14 10:48
We're currently preparing to release [v2.0.5 of the Stacks blockchain node](https://github.com/blockstack/stacks-blockchain/releases/tag/2.0.5) to Hiro PBC infrastructure that will resolve this problem API-side for wallet.

Thanks everyone for your patience here in the meantime 🙏

**Comment by markmhx** [comment] 2021-02-14 10:49
> If nothing changes and the wallet continues as-is, how delayed is the API used by the wallet so that I can send my token to the pool to join the rest of my stx?

I believe that only the latest round of unlocked STX are not showing up in the balance provided by the API and therefore unavailable for sending in the wallet at this time. Any previously unlocked STX should show up fine.

**Comment by markmhx** [comment] 2021-02-16 15:23
The API-side fix for this bug is now live! Please check your balances in the wallet and let us know if you still don't see the right amounts.

**Closed by markmhx** 2021-02-16 15:23 UTC
Labels: P1, bug

**Comment by Esharifov** [comment] 2021-02-17 01:22
I can confirm that issues is resolved on my wallet

**Comment by ounrequitedo** [comment] 2021-02-17 03:23
Ditto and thank you very much for the explanation and quick turnaround fix.

**Comment by jlyst** [comment] 2021-02-17 20:45
Yes, thank you for fix. Works for me now too.
