### ISSUE TITLE
Fix faucet for testnet version

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-wallet#878] opened 2021-07-23 13:11 UTC
I'm getting a "400: Bad Request" error when trying to request faucet STX with the testnet version of https://github.com/blockstack/stacks-wallet-web/pull/1430

![image](https://user-images.githubusercontent.com/28991/126786487-9cdf4143-90e1-447e-8c12-41244fb87862.png)

> {
  "error": "Error: Response 400: Bad Request fetching http://stacks-node-follower-microblocks.staging-stacks.svc.cluster.local:20443/v2/transactions - {\"error\":\"transaction rejected\",\"reason\":\"NotEnoughFunds\",\"reason_data\":{\"actual\":\"0x00000000000000000000000000000069\",\"expected\":\"0x0000000000000000000000001dcd65b4\"},\"txid\":\"97a428e407474b2dce14bf75ba78782f4b786675d05c736219417f38c375dcad\"}",
  "stack": "Error: Response 400: Bad Request fetching http://stacks-node-follower-microblocks.staging-stacks.svc.cluster.local:20443/v2/transactions - {\"error\":\"transaction rejected\",\"reason\":\"NotEnoughFunds\",\"reason_data\":{\"actual\":\"0x00000000000000000000000000000069\",\"expected\":\"0x0000000000000000000000001dcd65b4\"},\"txid\":\"97a428e407474b2dce14bf75ba78782f4b786675d05c736219417f38c375dcad\"}\n    at StacksCoreRpcClient.fetchText (/app/src/core-rpc/client.ts:132:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at StacksCoreRpcClient.fetchJson (/app/src/core-rpc/client.ts:111:26)\n    at StacksCoreRpcClient.sendTransaction (/app/src/core-rpc/client.ts:194:20)\n    at /app/src/api/routes/faucets.ts:222:25\n    at run (/app/node_modules/p-queue/dist/index.js:163:29)",
  "errorTag": "6820b5a5-2acb-4022-a85b-22b1826e2d76"
}

cc @beguene

**Comment by beguene** [comment] 2021-07-26 11:13
I am getting this error also in the web wallet. I think it's an issue with the api
Even if I make a simple POST request to https://stacks-node-api.testnet.stacks.co/extended/v1/faucets/stx?address=STG74KAPV1XM84BGSMFJAQAVGAHD17CA4CJPVRBD
I get  500 Internal Server Error with 
`{
    "error": "Error: Response 400: Bad Request fetching http://stacks-node-follower-green.staging-stacks.svc.cluster.local:20443/v2/transactions - {\"error\":\"transaction rejected\",\"reason\":\"TooMuchChaining\",\"reason_data\":{\"actual\":450,\"expected\":449,\"is_origin\":true,\"message\":\"Nonce would exceed chaining limit in mempool\",\"principal\":\"ST2QKZ4FKHAH1NQKYKYAYZPY440FEPK7GZ1R5HBP2\"},\"txid\":\"d88c798ddb4024ec166ffdc8747de62f8cad5dbd0d7f3418897cb368127259e4\"}",
    "stack": "Error: Response 400: Bad Request fetching http://stacks-node-follower-green.staging-stacks.svc.cluster.local:20443/v2/transactions - {\"error\":\"transaction rejected\",\"reason\":\"TooMuchChaining\",\"reason_data\":{\"actual\":450,\"expected\":449,\"is_origin\":true,\"message\":\"Nonce would exceed chaining limit in mempool\",\"principal\":\"ST2QKZ4FKHAH1NQKYKYAYZPY440FEPK7GZ1R5HBP2\"},\"txid\":\"d88c798ddb4024ec166ffdc8747de62f8cad5dbd0d7f3418897cb368127259e4\"}\n    at StacksCoreRpcClient.fetchText (/app/src/core-rpc/client.ts:125:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at StacksCoreRpcClient.fetchJson (/app/src/core-rpc/client.ts:104:26)\n    at StacksCoreRpcClient.sendTransaction (/app/src/core-rpc/client.ts:165:20)\n    at /app/src/api/routes/faucets.ts:222:25\n    at run (/app/node_modules/p-queue/dist/index.js:163:29)",
    "errorTag": "9aaf4538-01d7-4478-bb69-f4e242cd7f1d"
}`

It could be caused by our recent testnet reset.
cc: @zone117x

**Comment by GinaAbrams** [comment] 2021-07-26 18:21
Is there any work around for this? I keep running into the issue.

**Comment by andresgalante** [comment] 2021-07-26 18:43
Hi @GinaAbrams. We'll not pick any new issue that's not urgent this week to focus microblcoks. If it can wait, I'll bring it up next week.

**Comment by GinaAbrams** [comment] 2021-07-26 19:00
This error keeps popping up for me. It has been when trying to use the web wallet in the btc.us app to transfer or register a name. Not sure if just me or if there is a workaround but not the best user experience.

**Comment by aulneau** [comment] 2021-07-26 19:02
> This error keeps popping up for me. It has been when trying to use the web wallet in the btc.us app to transfer or register a name. Not sure if just me or if there is a workaround but not the best user experience.

This is a testnet error @GinaAbrams, are you sure we're on the right issue?

**Comment by aulneau** [comment] 2021-07-26 19:08
I see, he closed it in favor of https://github.com/blockstack/stacks-wallet-web/issues/1482

**Comment by beguene** [comment] 2021-08-02 14:17
This is working fine now. It might have been an issue with the testnet faucet at that time.

**Closed** 2021-08-02 15:00 UTC
Labels: P2, bug
