### ISSUE TITLE
User enters the 24 word seed phrase from the OLD software wallet into the new software wallet but DOES NOT get the same address

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-wallet#236] opened 2020-09-14 14:34 UTC
**Describe the bug**
Go to the old wallet create a new software wallet record your seed phrase, enter it into the new wallet the address is not the same

Older softwallet vs new softwaller with same 24 word seed phrase

Old software wallet
SPPFA4SAHA8Q01CX96CTYSCN153H9XM80CK6NC6Y

New software wallet
STPFA4SAHA8Q01CX96CTYSCN153H9XM80DCJWZEC

**To Reproduce**
1. Go to  the old wallet
2. Click on create new software wallet
3. Record the 24 word seed phrase then go into the wallet and record the address
4. Go to the new stacks 2.0 wallet select the option that you have a wallet then enter the 24 word seed phrase.
5. Select recieve to view the address and the addresses are NOT the same

**Expected behavior**
The decryption should be the same and should return the same address
**Screenshots**
<img width="933" alt="Screen Shot 2020-09-14 at 10 21 45 AM" src="https://user-images.githubusercontent.com/49165468/93099010-83bc8c80-f675-11ea-9356-efb4723a9220.png">
<img width="691" alt="Screen Shot 2020-09-14 at 10 25 53 AM" src="https://user-images.githubusercontent.com/49165468/93099012-84552300-f675-11ea-9aa7-542d71e3b9ee.png">
<img width="695" alt="Screen Shot 2020-09-14 at 10 23 19 AM" src="https://user-images.githubusercontent.com/49165468/93099013-84552300-f675-11ea-8766-d6486abde192.png">

**Desktop (please complete the following information):**
 - OS:  iOS
 
**Additional context**

**Comment by markmhx** [comment] 2020-10-30 13:31
This testing may need testnet genesis block assistance per https://github.com/blockstackpbc/devops/issues/490

**Comment by aulneau** [comment] 2021-01-07 19:06
```
➜  ~ stx convert_address -t SPPFA4SAHA8Q01CX96CTYSCN153H9XM80CK6NC6Y 
{
  "mainnet": {
    "STACKS": "SPPFA4SAHA8Q01CX96CTYSCN153H9XM80CK6NC6Y",
    "BTC": "156iKYNXSBd4bJTuJJ1ism5qrfJ5dDui9Q"
  },
  "testnet": {
    "STACKS": "STPFA4SAHA8Q01CX96CTYSCN153H9XM80DCJWZEC",
    "BTC": "mjcfcbTWFD4KNQwX1rz6hgJAietnV3Unvq"
  }
  ```

**Comment by timstackblock** [comment] 2021-01-08 14:37
v2 mainnet wallet, stacks-wallet-4.0.0-beta.7-mainnet-windows still have different addresses when a user opens the wallet with the same ledger. 
 
SP2MQ90MTF6SNZ9KA6BG03BR6RSJ2C3W9GW86ZNGK

![Screenshot (2)](https://user-images.githubusercontent.com/49165468/104027201-e503f080-517b-11eb-823b-b05ea80217b9.png)

**Comment by aulneau** [comment] 2021-01-08 14:48
@timstackblock yeah the issue is that the wallet for stacks 2.0 is returning the testnet version of the wallet address, which you can see from the output (regardless of the build version).

I believe @kyranjamie has made updates to fix this, so when that release is out, you should try again with a mainnet build and confirm they are the same.

An easy way to tell if an address is mainnet/testnet is this:

mainnet -> starts with "SP" or "SM"
testnet -> starts with "ST"

It's good that the two STACKS addresses from the cli match the two addresses shown in the screenshot. If they didn't that would be a much bigger issue.

**Comment by timstackblock** [comment] 2021-01-08 14:49
I just tried it doesn't work this is with the fix he released lastnight

**Comment by aulneau** [comment] 2021-01-08 14:50
I'll let @kyranjamie confirm if it's ready or not

**Comment by timstackblock** [comment] 2021-01-08 14:54
This was the fix https://github.com/blockstack/stacks-wallet/pull/467, we still have issues

**Comment by kyranjamie** [comment] 2021-01-15 10:07
I completely missed this thread, and this was a crucial find @timstackblock. Sorry to everyone for not following up.

As I later discovered, this indeed demos the issue of the Ledger only creating testnet addresses. It turned out the version bytes were the wrong way around. These were flipped, so it will **only** create mainnet addresses. There was some confusion around BIP-44 compliance and use of derivation paths. Further updates to the Ledger app can be made to reintroduce the ability to generate mainnet & testnet addresses from the same derivation path if needed.

**Comment by markmhx** [comment] 2021-01-15 10:19
Related issues filed here: https://github.com/blockstack/stacks-wallet/issues/510 https://github.com/blockstack/stacks-wallet/issues/510

I'm going to close this issue out in favor of those (or other new issues) related to address generation with Ledger.

**Closed by markmhx** 2021-01-15 10:19 UTC
Labels: enhancement
